reddit_remake/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import (index_view, AllSubredditView, SubredditView, PostView,
                       SubredditUpdateView, SubredditCreateView, PostCreateView,
                       PostUpdateView, UserCreateView, CommentUpdateView)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', index_view, name="index_view"),
    url(r'^create_user/$', UserCreateView.as_view(), name="user_create_view"),
    url(r'^subreddits/$', AllSubredditView.as_view(), name="all_subreddit_view"),
    url(r'^subreddits/(?P<pk>\d+)/$', SubredditView.as_view(), name="subreddit_view"),
    url(r'^subreddits/create/$', SubredditCreateView.as_view(), name="subreddit_create_view"),
    url(r'^subreddits/(?P<pk>\d+)/update/$', SubredditUpdateView.as_view(), name="subreddit_update_view"),
    url(r'^post/(?P<pk>\d+)/$', PostView.as_view(), name="post_view"),
    url(r'^subreddits/(?P<pk>\d+)/post/create/$', PostCreateView.as_view(), name="post_create_view"),
    url(r'^post/(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name="post_update_view"),
    url(r'^comment/(?P<pk>\d+)/update/$', CommentUpdateView.as_view(), name="comment_update_view")

]

app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.


class Subreddit(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    creation_time = models.DateTimeField(auto_now_add=True)

    def current_count(self):
        return Post.objects.filter(relation_subreddit=self).count()

    def today_count(self):
        return Post.objects.filter(creation_time__gt=self.creation_time + datetime.timedelta(hours=-24)).count()

    def daily_average(self):
        past_week = Post.objects.filter(creation_time__gt=self.creation_time + datetime.timedelta(days=-7)).count()
        return round((past_week / 7), 2)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=255)
    url = models.URLField(null=True, blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    modification_time = models.DateTimeField(auto_now=True)
    relation_subreddit = models.ForeignKey(Subreddit)
    relation_user = models.ForeignKey(User)

    def is_recent(self):
        now = timezone.now()
        if self.creation_time >= now + datetime.timedelta(hours=-24):
            return True
        else:
            return False

    def is_hot(self):
        now = timezone.now()
        post_comments = Comment.objects.filter(relation_post=self)
        hot_comments = []
        for item in post_comments:
            if item.creation_time >= now + datetime.timedelta(hours=-3):
                hot_comments.append(item)
        if len(hot_comments) >= 3:
            return True
        else:
            return False

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-creation_time",)


class Comment(models.Model):
    content = models.CharField(max_length=255)
    relation_user = models.ForeignKey(User)
    relation_post = models.ForeignKey(Post)
    creation_time = models.DateTimeField(auto_now_add=True)
    modification_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ("-creation_time",)


class Profile(models.Model):
    user = models.OneToOneField('auth.User')
    random_fact = models.CharField(max_length=100, null=True)


@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get('created')
    instance = kwargs.get('instance')
    if created:
        Profile.objects.create(user=instance)

app/forms.py
from django import forms
from app.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        fields = ("content",)
        model = Comment


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("title", "content", "url")
        model = Post

app/views.py
from django.shortcuts import render
from app.models import Comment, Post, Subreddit, Profile
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from app.forms import CommentForm, PostForm
from django.urls import reverse, reverse_lazy

# Create your views here.


def index_view(request):
    context = {
        "all_posts": Post.objects.all()

    }
    return render(request, "index.html", context)


class AllSubredditView(ListView):
    model = Subreddit
    template_name = "subreddits.html"


class SubredditView(DetailView):
    model = Subreddit


class SubredditCreateView(CreateView):
    model = Subreddit
    success_url = "/subreddits"
    fields = ("name", "description")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.relation_user = self.request.user
        return super().form_valid(form)


class SubredditUpdateView(UpdateView):
    model = Subreddit
    success_url = "/subreddits"
    fields = ("name", "description")


class PostView(CreateView):
    model = Comment
    fields = ("content",)
    template_name = "app/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        context['post'] = Post.objects.get(id=self.kwargs["pk"])
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.relation_user = self.request.user
        instance.relation_post = Post.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        post_id = self.kwargs['pk']
        return "/post/{}/".format(post_id)


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.relation_user = self.request.user
        instance.relation_subreddit = Subreddit.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        subreddit_id = self.kwargs['pk']
        return "/subreddits/{}/".format(subreddit_id)


class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'content', 'url')

    def get_success_url(self):
        post_id = self.kwargs['pk']
        return "/post/{}/".format(post_id)


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ("content",)
    success_url = reverse_lazy("post_view")

    # def get_success_url(self):
    #     return "/subreddits/"


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = "/"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super().form_valid(form)

templates/app/comment_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Comment</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

templates/app/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>
<h4>{{ post.content }}</h4>
<br>
<h5>Posted by: {{ post.relation_user }}</h5>
<h6>{{ post.creation_time|timesince }} ago</h6>
<p>
  {% if post.is_recent %}
    This post is recent!
  {% endif %}<br>
  {% if post.is_hot %}
    This post is HOT!
  {% endif %}<br>
  {% if request.user == post.relation_user %}
  <font color="#000000"><a href="{% url 'post_update_view' post.id %}">Update Post</a></font>
  {% endif %}
</p>
<form class="" action="" method="post">
  {% csrf_token %}
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
        Post a comment!<br>{{ form }}
      </p>
      <input class="btn btn-default" type="submit" value="Submit">
    </div>
  </div>
</form>
{% for comment in post.comment_set.all %}
  <div class="panel panel-default">
    <div class="panel-body">
      {{ comment.content }}
    </div>
    <div class="panel-footer">By: {{ comment.relation_user }}
      <font size="1">{{ comment.creation_time|timesince }} ago</font>
      {% if request.user == comment.relation_user %}
      <div class="pull-right">
        <font size="2"><a href="{% url 'comment_update_view' comment.id %}">Update Comment</font></a>
      </div>
      {% endif %}
    </div>
  </div>
{% endfor %}
{% endblock %}

templates/app/post_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Create a Post!</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="name" value="Submit">
</form>
{% endblock %}

templates/app/subreddit_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ object.name }}</h1>
<h4>{{ object.description }}</h4>
<h6><a href="{% url 'subreddit_update_view' object.id %}"><font color="#FFFFFF">Update Subreddit</font></a></h6>
<h6><a href="{% url 'post_create_view' object.id %}"><font color="#FFFFFF">Create Post</font></a></h6>
{% for post in object.post_set.all|slice:":20" %}
<ul class="list-group">
  <li class="list-group-item">
    <span class="badge">{{ post.comment_set.count }}</span>
    <a href="{% url 'post_view' post.id %}"><font color="#ed7a23">{{ post.title }}</font></a>
  </li>
</ul>
{% endfor %}
{% endblock %}

templates/app/subreddit_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Create a Subreddit!</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Reddit Remake</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen" title="no title">
    <style media="screen">
      body {
        background-color: #2b63bc;
        color: #ed7a23;

      }
    </style>
  </head>
  <body link="#000000" vlink="#FFFFFF">
    <div class="container">
      |<a href="{% url 'index_view' %}"><font color="#FFFFFF"> Home </font></a>|
      <a href="{% url 'all_subreddit_view' %}"><font color="#FFFFFF"> All Subreddits </font></a>|
      <a href="{% url 'subreddit_create_view' %}"><font color="#FFFFFF"> Create Subreddit </font></a>|
      {% if not request.user.is_authenticated %}
        <a href="{% url 'login' %}"><font color="#FFFFFF"> Login </font></a>|
        <a href="{% url 'user_create_view' %}"><font color="#FFFFFF"> Create User </font></a>|
      {% else %}
        <a href="{% url 'logout' %}?next={% url 'index_view' %}"><font color="#FFFFFF"> Logout </font></a>|
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to antiReddit!</h1>
<h3>{{ request.user }}</h3>
<p>
  This is your place to post anything you want about any category.<br>
  Create a subreddit, post on an existing subreddit, or comment on existing posts! <br>
  Create a user to get started!
</p>
{% endblock %}

templates/subreddits.html
{% extends 'base.html' %}
{% block content %}
<h1>All Subreddits</h1>
{% for sub in object_list %}
<div class="panel panel-default">
  <div class="panel-heading">
  <a href="{% url 'subreddit_view' sub.id %}"><h3 class="panel-title">{{ sub.name }}</h3></a>
  </div>
  <div class="panel-body">
    <h5>{{ sub.description }}</h5>{{ sub.current_count }} posts
  </div>
</div>
{% endfor %}
{% endblock %}